### ISSUE TITLE
Change VM Background

### ISSUE THREAD

**Issue by mwhittaker** [cs3110/tools#125]
I think I remember that when some students went to download the most recent version of the 3110 VM, they accidentally downloaded a VM from a previous semester which led to quite a bit of confusion. I recommend changing the [background image](https://github.com/cs3110/tools/blob/master/config/background.jpg) of the VM to something new so that the newest VM can be easily distinguished from older VMs.

**Comment by gfh47** [comment]
+1 great idea!

**Comment by mwhittaker** [comment]
Thanks, Grant! There's [lots of cool camel wallpapers](https://images.google.com/?q=camel%20wallpaper) to choose from too!

**Comment by bkc39** [comment]
Why is this not a picture of zardoz?



—

**Comment by mwhittaker** [comment]
Haha, good idea Ben! There are some pretty psychedelic zardoz wallpapers:

![zardoz](https://jaysanalysis.files.wordpress.com/2015/03/h7prtsoqgo5eabods25sfdgdfmk.jpg)

**Comment by remyjette** [comment]
...I like it, but I think it *might* terrify the students...considering it's terrifying me right about now =D

**Comment by remyjette** [comment]
Also @mwhittaker - I made the name of the VM "cs3110-2015fa" so it'll get imported as such in VirtualBox, making it easy for us to see what VM version it is...but if you want to commit a new wallpaper to https://github.com/cs3110/tools/blob/master/config/background.jpg I can rebuild the VM...

**Comment by mwhittaker** [comment]
@remyjette, renaming the VM was a good idea! Rebuilding the VM probably isn't worth it. Maybe next semester the time will come for a zardoz wallpaper.
